# Generated by Django 5.0.8 on 2026-05-15 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('INTAKE', 'Intake'), ('OCR_EXTRACTION', 'OCR & Extraction'), ('IDENTITY_VERIF', 'Identity Verification'), ('ADDRESS_VERIF', 'Address Verification'), ('AML_RISK', 'AML Risk Scoring'), ('COMPLIANCE_REVIEW', 'Compliance Review'), ('CKYC_UPLOAD', 'CKYC Upload'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='INTAKE', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CaseAgentTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('log', models.TextField()),
                ('thought', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='cases.case')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
